/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ansh
 */
import java.sql.*;
import javax.swing.*;
public class Login extends java.awt.Frame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        user_name = new java.awt.Label();
        user_name_data = new java.awt.TextField();
        password = new java.awt.Label();
        password_data = new java.awt.TextField();
        login = new java.awt.Button();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book1.jpg"))); // NOI18N
        jLabel1.setText("Forgot Password?");

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        user_name.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        user_name.setText("Username");
        add(user_name);
        user_name.setBounds(47, 49, 87, 28);

        user_name_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_name_dataActionPerformed(evt);
            }
        });
        add(user_name_data);
        user_name_data.setBounds(216, 49, 111, 28);

        password.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        password.setText("Password");
        add(password);
        password.setBounds(47, 143, 82, 29);

        password_data.setEchoChar('*');
        add(password_data);
        password_data.setBounds(216, 143, 111, 29);

        login.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        login.setLabel("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        add(login);
        login.setBounds(50, 240, 61, 33);

        button1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        button1.setLabel("Reset");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(320, 240, 61, 33);

        button2.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        button2.setLabel("Forgot Password?");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2);
        button2.setBounds(140, 240, 150, 33);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void user_name_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_name_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_name_dataActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String user_name = user_name_data.getText();
        String password = password_data.getText();        
        
        if(password.length() < 8) {
            JOptionPane.showMessageDialog(null, "Password should be atleast than 8 characters.");    
        }
        else {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login", "root", "");
            String query = "SELECT * FROM `username` WHERE `Username` =? AND `Password` =?";
            Statement stmt = con.createStatement();
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, user_name);
            ps.setString(2, password);
            ResultSet rs = ps.executeQuery();
            
            if(user_name.equals("admin") && password.equals("administrator")) {
                JOptionPane.showMessageDialog(null,"Welcome Admin!");
                Add a = new Add();
                setVisible(false);
                a.setVisible(true);
            }
            else if(rs.next())
            {
                     JOptionPane.showMessageDialog(null,"Login Successfull");                     
                     setVisible(false);
                     Home i = new Home(user_name,rs.getString("Name"));
                     i.setVisible(true);
           }
            else{
                 JOptionPane.showMessageDialog(null,"Login Unsuccessfull");
                    user_name_data.setText("");
                    password_data.setText("");
            }
        }
        catch(Exception e){
            
        }
        }
        
        
    }//GEN-LAST:event_loginActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
       
        user_name_data.setText(" ");
       password_data.setText(" ");
        user_name_data.setText("");
       password_data.setText("");
       
    }//GEN-LAST:event_button1ActionPerformed

    /*private void password_dataKeyUp(java.awt.event.KeyEvent evt) {
        password_data.setEchoChar('*');
    }*/
    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
       
    }//GEN-LAST:event_button1MouseClicked

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Forget_Passwd fpwd = new Forget_Passwd();
        fpwd.setVisible(true);
    }//GEN-LAST:event_button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Button login;
    private java.awt.Label password;
    private java.awt.TextField password_data;
    private java.awt.Label user_name;
    private java.awt.TextField user_name_data;
    // End of variables declaration//GEN-END:variables
}
