
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bhavesh
 */
public class New_Pwd extends javax.swing.JFrame {
String uname;
    /**
     * Creates new form New_Pwd
     */
    public New_Pwd() {        
        initComponents();
    }
    public New_Pwd(String uname){
            initComponents();
        this.uname=uname;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pwd = new java.awt.Label();
        button1 = new java.awt.Button();
        password = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pwd.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        pwd.setText("Enter New Password");
        getContentPane().add(pwd);
        pwd.setBounds(101, 38, 171, 29);

        button1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        button1.setLabel("Update");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(151, 180, 99, 33);

        password.setEchoChar('*');
        getContentPane().add(password);
        password.setBounds(101, 89, 200, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        password.setEchoChar('*');
        String new_pwd=password.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login", "root", "");
            String query="SELECT `Password` FROM `username` WHERE `Username`=?";                        
                            PreparedStatement ps = con.prepareStatement(query); 
                           ps.setString(1,uname);
                            ResultSet rs=ps.executeQuery();         
                            while(rs.next()){
                            if(new_pwd.equals(rs.getString("Password")))
                            {
                                JOptionPane.showMessageDialog(null,"Please Enter Another Password");
                            }
                            else{
                                    String query1="UPDATE `username` SET `Password` =? WHERE `Username`=?";
                                    PreparedStatement ps1 = con.prepareStatement(query1);
                                    ps1.setString(1, new_pwd);
                                    ps1.setString(2,uname);
                                    int num=ps1.executeUpdate();
                                    if(num>0){
                                        JOptionPane.showMessageDialog(null,"Success! Please login with new password now.");
                                        Login l = new Login();
                                        setVisible(false);
                                        l.setVisible(true);
                                    }
                            }
                            }                           
                            Login l=new Login();
                             setVisible(false);
                            l.setVisible(true);
                            
            
            
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Pwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Pwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Pwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Pwd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_Pwd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private java.awt.TextField password;
    private java.awt.Label pwd;
    // End of variables declaration//GEN-END:variables
}
