/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bhavesh
 */
import java.sql.*;
import javax.swing.*;
public class Register extends java.awt.Frame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new java.awt.Label();
        Lname = new java.awt.Label();
        Uname = new java.awt.Label();
        Pwd = new java.awt.Label();
        pin = new java.awt.Label();
        name = new java.awt.TextField();
        lname = new java.awt.TextField();
        uname = new java.awt.TextField();
        pwd = new java.awt.TextField();
        spin = new java.awt.TextField();
        Register = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        Name.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        Name.setText("Name");
        add(Name);
        Name.setBounds(340, 70, 54, 29);

        Lname.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        Lname.setText("Last Name");
        add(Lname);
        Lname.setBounds(340, 130, 92, 29);

        Uname.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        Uname.setText("UserName");
        add(Uname);
        Uname.setBounds(340, 180, 91, 29);

        Pwd.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        Pwd.setText("Password");
        add(Pwd);
        Pwd.setBounds(340, 240, 82, 29);

        pin.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        pin.setText("Security Pin");
        add(pin);
        pin.setBounds(340, 290, 98, 29);

        name.setText(" ");
        add(name);
        name.setBounds(560, 70, 112, 20);
        add(lname);
        lname.setBounds(560, 130, 112, 20);
        add(uname);
        uname.setBounds(560, 190, 112, 20);

        pwd.setEchoChar('*');
        add(pwd);
        pwd.setBounds(560, 250, 112, 20);
        add(spin);
        spin.setBounds(560, 300, 112, 20);

        Register.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        Register.setLabel("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        add(Register);
        Register.setBounds(480, 360, 82, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 880, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
        int x=0; boolean b = false;
        String first_name=name.getText();
        String last_name=lname.getText();
        String U_name=uname.getText();
        String Pwd=String.valueOf(pwd.getText());       
        String Security=spin.getText();
        String data_check=null;
        
          if(first_name==" "){
              data_check+="Name"; 
          JOptionPane.showMessageDialog(null, "Name");}
          if(last_name==null)
               data_check+="Last Name ";
          if(U_name==null)
              data_check+="User Name ";
          if(Pwd==null)
              data_check+="Password ";
          if(Security==null)
              data_check+="Security Data";
          
          try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login", "root", "");
        
                String tp = "SELECT * From `username` WHERE `Username`=?";
                PreparedStatement ps1 = con.prepareStatement(tp);
                ps1.setString(1,U_name);
                b = ps1.execute(); 
        }
        catch(Exception e){
            System.out.print(e);
        }
          
          if(Pwd.length() < 8) {
            JOptionPane.showMessageDialog(null, "Password should be atleast than 8 characters.");    
          }
          else if (b != false ) {
            JOptionPane.showMessageDialog(null, "Username already exists! Please log in.");
            Login l = new Login();
            setVisible(false);
            l.setVisible(true);
          }
          else {
          if(data_check==null){              
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login", "root", "");
            String query =  "INSERT INTO `username`(`Username`, `Password`,`Security`,`Name`,`Lname`) VALUES (?,?,?,?,?)";                       
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, U_name);
            ps.setString(2, Pwd);
            ps.setString(3,Security);
            ps.setString(4,first_name);
            ps.setString(5,last_name);
            ps.executeUpdate();
            x++;
           if(x > 0)
            {
                JOptionPane.showMessageDialog(null, "New User Add");
                setVisible(false);
                Login l = new Login();
                l.setVisible(true);                
            }
           con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
          }
          else{
          JOptionPane.showMessageDialog(null,"Type In:"+data_check);
          }
          }         
    }//GEN-LAST:event_RegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Lname;
    private java.awt.Label Name;
    private java.awt.Label Pwd;
    private java.awt.Button Register;
    private java.awt.Label Uname;
    private javax.swing.JLabel jLabel1;
    private java.awt.TextField lname;
    private java.awt.TextField name;
    private java.awt.Label pin;
    private java.awt.TextField pwd;
    private java.awt.TextField spin;
    private java.awt.TextField uname;
    // End of variables declaration//GEN-END:variables
}
