
import javax.swing.JOptionPane;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ansh
 */
public class Return extends javax.swing.JFrame {
    String username,name;
    /**
     * Creates new form Return
     */
    public Return(String u, String n){
        username = u;
        name = n;
        initComponents();
    }
    public Return() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        choice1 = new java.awt.Choice();
        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        label1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        label1.setText("Select the book you want to return");
        getContentPane().add(label1);
        label1.setBounds(59, 39, 285, 29);

        choice1.setName("AA"); // NOI18N
        getContentPane().add(choice1);
        choice1.setBounds(60, 90, 191, 33);

        button1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        button1.setLabel("Return");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(167, 199, 69, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login", "root", "");
            //String query = "SELECT * from record";
            String query = "SELECT `Name` FROM record WHERE `Username`=? AND `Returned`=false";          
            PreparedStatement ps = con.prepareStatement(query);  
            ps.setString(1,username);
            ResultSet rs = ps.executeQuery();            
            while(rs.next())                      
                choice1.add(rs.getString("Name"));            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login", "root", "");
            String query = "UPDATE record SET `Returned`=true WHERE `Username`=? AND `Name`=?";      
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, username);
            ps.setString(2, choice1.getSelectedItem());
            ps.execute();
            
            JOptionPane.showMessageDialog(null, "Book returned successfully!");            
            
            String query2 = "Select * from books where `name`=? ";
            PreparedStatement ps2 = con.prepareStatement(query2);
            ps2.setString(1, choice1.getSelectedItem());
            ResultSet rs = ps.executeQuery();
            int stock = rs.getInt("stock");
            stock++;
            String query3 = "UPDATE books SET stock="+stock+";";
            Statement stmt = con.createStatement();
            stmt.execute(query3);     
            
            stmt.close();
            ps.close();
            ps2.close();
            con.close();
            
            Home h = new Home(username,name);
            setVisible(false);
            h.setVisible(true);
            
        }
        catch(Exception e) {
            
        }
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param evt
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Choice choice1;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
